### PR TITLE
Switched to new nuget package restore approach

### PR DESCRIPTION
**Pull request by JakeGinnivan**
The targets file approach is no longer recommended. So am just removing it and cleaning up the projects still referencing it

### CODE REVIEW

**Comment by plioi** [comment]
I don't necessarily object to the R# settings changes, but do you know what settings those are?

**Comment by JakeGinnivan** [comment]
Oops, didn't realise that had changed. But looks like a flag to say a particular migration has run so it shouldn't cause any issues. I can revert tomorrow if you would like.

Sent from my Windows Phone
________________________________

**Comment by plioi** [comment]
If that's all it's talking about, no need to change it.  Thanks.

**Comment by plioi** [comment]
After doing some research, I found that 1) there was more that could be removed and 2) my nuget.exe and corresponding build.cmd both needed updating to agree with the new style as well.  I just pushed these to master at 9d080b64fce62ced7a09b912dcdb0be1288a1173

**Comment by JakeGinnivan** [comment]
:+1:

**Pull request closed without merging**
